blank_issues_enabled: false
contact_links:
  - name: Güvenlik Bildirimi
    url: https://github.com/muhammedeminalan
    about: Güvenlik ile ilgili hassas konular için proje sahibiyle özel iletişim kurun.

